# Form implementation generated from reading ui file 'modewindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ModeWindow(object):
    def setupUi(self, ModeWindow):
        ModeWindow.setObjectName("ModeWindow")
        ModeWindow.resize(451, 401)
        self.centralwidget = QtWidgets.QWidget(parent=ModeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.square_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.square_radio.setGeometry(QtCore.QRect(30, 110, 82, 17))
        self.square_radio.setObjectName("square_radio")
        self.rectange_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.rectange_radio.setGeometry(QtCore.QRect(30, 160, 82, 17))
        self.rectange_radio.setObjectName("rectange_radio")
        self.triangle_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.triangle_radio.setGeometry(QtCore.QRect(30, 210, 82, 17))
        self.triangle_radio.setObjectName("triangle_radio")
        self.text1 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.text1.setGeometry(QtCore.QRect(170, 100, 251, 31))
        self.text1.setObjectName("text1")
        self.label_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(120, 110, 47, 13))
        self.label_1.setObjectName("label_1")
        self.text2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.text2.setGeometry(QtCore.QRect(170, 150, 251, 31))
        self.text2.setObjectName("text2")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 160, 47, 16))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.comput_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.comput_button.setGeometry(QtCore.QRect(190, 260, 75, 23))
        self.comput_button.setObjectName("comput_button")
        self.result_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(110, 220, 251, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.result_label.setFont(font)
        self.result_label.setText("")
        self.result_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.result_label.setObjectName("result_label")
        self.circle_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.circle_radio.setGeometry(QtCore.QRect(30, 60, 82, 17))
        self.circle_radio.setObjectName("circle_radio")
        ModeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ModeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 451, 21))
        self.menubar.setObjectName("menubar")
        ModeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ModeWindow)
        self.statusbar.setObjectName("statusbar")
        ModeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ModeWindow)
        QtCore.QMetaObject.connectSlotsByName(ModeWindow)

    def retranslateUi(self, ModeWindow):
        _translate = QtCore.QCoreApplication.translate
        ModeWindow.setWindowTitle(_translate("ModeWindow", "ModeWindow"))
        self.square_radio.setText(_translate("ModeWindow", "Square"))
        self.rectange_radio.setText(_translate("ModeWindow", "Rectangle"))
        self.triangle_radio.setText(_translate("ModeWindow", "Triangle"))
        self.label_1.setText(_translate("ModeWindow", "Radius"))
        self.comput_button.setText(_translate("ModeWindow", "COMPUTE"))
        self.circle_radio.setText(_translate("ModeWindow", "Circle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ModeWindow = QtWidgets.QMainWindow()
    ui = Ui_ModeWindow()
    ui.setupUi(ModeWindow)
    ModeWindow.show()
    sys.exit(app.exec())
